defaults: &defaults
  fog_provider: 'AWS'
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  existing_remote_files: keep
  # To delete existing remote files.
  # existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults
  enabled: true
  fog_directory: "foodrubix-testing"


production:
  <<: *defaults
  enabled: true
  fog_directory: "foodrubix-production"
